Do not urlencode local file paths
urlencoding the file path when using local files as input breaks the script:

    $ w3c-validator.py --verbose "EPUB 2/OEBPS/part038.html" 
    validating: EPUB 2/OEBPS/part038.html ...
    curl -sF "uploaded_file=@EPUB%202/OEBPS/part038.html;type=text/html" -F output=json http://validator.w3.org/check
    Traceback (most recent call last):
      File "/Users/jorge/bin/w3c-validator.py", line 81, in <module>
        result = validate(f)
      File "/Users/jorge/bin/w3c-validator.py", line 56, in validate
        raise OSError (status, 'failed: %s' % cmd)
    OSError: [Errno 6656] failed: curl -sF "uploaded_file=@EPUB%202/OEBPS/part038.html;type=text/html" -F output=json http://validator.w3.org/check

Not doing so works fine:

    $ w3c-validator.py --verbose "EPUB 2/OEBPS/part038.html" 
    validating: EPUB 2/OEBPS/part038.html ...
    curl -sF "uploaded_file=@EPUB 2/OEBPS/part038.html;type=text/html" -F output=json http://validator.w3.org/check
    {
        "url": "part038.html",
        "messages": [
            
            ],
        "source": {
            "encoding": "utf-8",
            "type": "text/html"
        }
    }